num1 = int(input("please enter 5 number: "))
num2 = int(input("please enter 5 number: "))
num3 = int(input("please enter 5 number: "))
num4 = int(input("please enter 5 number: "))
num5 = int(input("please enter 5 number: "))

print(num1 + num5)
print(num2 - num4)
print(num3 * num3)
print(num4 / num2)
print(num5 % num1)